w1120/w02/home/urls.py
from django.urls import path,include
from . import views

app_name = ''
urlpatterns = [
    path('', views.index, name='index'),
]

w1120/w02/member/urls.py
from django.urls import path,include
from . import views

app_name = 'member'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mlist/', views.mlist, name='mlist'),
    path('cookWrite/', views.cookWrite, name='cookWrite'),
    path('cookDelete/', views.cookDelete, name='cookDelete'),
]

w1120/w02/w02/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('', include('home.urls')),
]

w1120/w02/member/models.py
from django.db import models

# Create your models here.

class Member(models.Model):
  id  = models.CharField(max_length=100,primary_key=True)
  pw = models.CharField(max_length=100,null=False)
  name = models.CharField(max_length=100)
  nicName = models.CharField(max_length=100,null=True)
  mdate = models.DateTimeField(auto_now=True)
  
  def __str__(self):
    return f"{self.id},{self.name},{self.nicName}"

w1120/w02/member/views.py
from django.shortcuts import render,redirect
from member.models import Member


def logout(request):
  # 섹션모두 삭제
  request.session.clear() # 섹션모두 삭제
  # del request.session['session_id'] # 해당 섹션만 삭제
  return redirect('index')


def login(request):
  if request.method == "GET":
    response = render(request,'login.html')
  else:
    emsg = ""
    id = request.POST.get("id")
    pw = request.POST.get("pw")
    qs = Member.objects.filter(id=id,pw=pw)
    if qs:
      context = {"emsg":emsg,"member":qs[0]}
      request.session['session_id'] = id
      request.session['session_nicName'] = qs[0].nicName
      response = render(request,'index.html',context)      
    else:
      emsg = "아이디 또는 패스워드가 일치하지 않습니다."
      context = {"emsg":emsg,"member":""}
      response = render(request,'login.html',context)      
  return response



def cookDelete(request):
  if request.method == "GET":
    response = render(request,'cookDelete.html')
  else:
    response = render(request,'index.html')
    c = request.POST.get('ckey')
    response.delete_cookie(c)
    print(c," 쿠키가 삭제되었습니다.")
  return response


def cookWrite(request):
  response = render(request,'cookWrite.html')
  if request.method == "GET":
    print("GET 방식으로 들어옴.")
  else:
    response = render(request,'index.html')
    print("POST 방식으로 들어옴.")
    ckey = request.POST.get('ckey')
    cvalue = request.POST.get('cvalue')
    response.set_cookie(ckey,cvalue)

  return response


def mlist(request):
  return render(request,'mlist.html')

w1120/w02/home/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>메인페이지</title>
</head>
<body>
  <h2>메인페이지</h2>
  <h4>쿠키정보{{request.COOKIES}}</h4>
  <h4>섹션정보{{request.session.session_id}}</h4>
  
  <ul>
    {% if not request.session.session_id %}
      <h4>로그인을 하셔야 더 많은 정보를 볼수 있습니다.</h4>
      <li><a href="/member/login/">로그인</a></li>
      {% else %}
      <h4>{{request.session.session_nicName}} 님 환영합니다.</h4>
      <li><a href="/member/logout/">로그아웃</a></li>
      <li><a href="/member/mlist/">회원리스트</a></li>
      <li><a href="/member/cookWrite/">쿠키만들기</a></li>
      <li><a href="/member/cookDelete/">쿠키삭제</a></li>
      <li><a href="/admin/">admin관리자</a></li>
    {% endif %}
  </ul>
  
</body>
</html>

w1120/w02/member/templates/cookDelete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>쿠키삭제</title>
  <style>
    div{width:200px; height:30px; border:1px solid black; }
  </style>
</head>
<body>
  <h2>쿠키삭제</h2>
  <form action="{% url 'member:cookDelete' %}" method="post" name="loginFrm">
    {% csrf_token %}
    {% for c in request.COOKIES %}
      <div>{{c}}</div>
    {% endfor %}
    <label>쿠키key</label>
    <input type='text' name='ckey' id='ckey' ><br>
    <input type='submit' value="쿠키삭제">
  </form>
  
</body>
</html>

w1120/w02/member/templates/cookWrite.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>쿠키만들기</title>
</head>
<body>
  <h2>쿠키만들기</h2>
  <form action="{% url 'member:cookWrite' %}" method="post" name="loginFrm">
    {% csrf_token %}
    <label>쿠키key</label>
    <input type='text' name='ckey' id='ckey' ><br>
    <label>쿠키value</label>
    <input type='text' name='cvalue' id='cvalue'><br>
    <input type='submit' value="쿠키저장">
  </form>
  
</body>
</html>

w1120/w02/member/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>로그인</title>
  <style>
    div{font-size:15px; color:red; font-weight:700;}
  </style>
  <script>
    if ( '{{emsg}}' != ''){
      alert('{{emsg}}')
    }
  </script>
</head>
<body>
  <h2>로그인</h2>
  <form action="{% url 'member:login' %}" method="post" name="loginFrm">
    {% csrf_token %}
    <div>{{emsg}}</div>
    <label>아이디</label>
    <input type='text' name='id' id='id' ><br>
    <label>패스워드</label>
    <input type='password' name='pw' id='pw'><br>
    <input type='checkbox' name='saveId' value='1' id='saveId'>
    <label for="saveId">아이디저장</label><br>
    <input type='submit' value="로그인">

  </form>
  
</body>
</html>

w1120/w02/member/templates/mlist.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>회원리스트</title>
  <style>
    *{margin:0; padding:0;}
    .main{margin:30px auto; text-align:center;}
    h2{margin:30px 0;}
    table,th,td{border:1px solid black; border-collapse:collapse;}
    table{width:1200px; margin:30px auto;}
    th,td{height:45px; width:200px;}
    button{width:120px; height:40px;}
    .search{width:190px; height:40px; padding-left:10px; margin-top:50px;}
  </style>
</head>
<body>
  <div class="main">
    <h2>회원리스트</h2>
    <table>
      <tr>
        <th>번호</th>
        <th>아이디</th>
        <th>패스워드</th>
        <th>이름</th>
        <th>닉네임</th>
        <th>가입일</th>
      </tr>
      
      
    </table>
    <button onclick="location.href='/'">홈으로</button>
    <button onclick="location.href='/member/mwrite/'" >회원정보입력</button>
  </div>
    
</body>
</html>