w1120/w01/member/urls.py
from django.urls import path,include
from . import views

app_name='member'
urlpatterns = [
    path('mlist/', views.mlist, name='mlist'),
    path('login/', views.login, name='login'),
    path('login2/', views.login2, name='login2'),
    path('product/', views.product, name='product'),
]

w1120/w01/member/models.py
from django.db import models


class Member(models.Model):
  id = models.CharField(max_length=50, primary_key=True)
  pw = models.CharField(max_length=100, blank=False)
  name = models.CharField(max_length=100)
  nicname = models.CharField(max_length=100)
  cdate = models.DateTimeField(auto_now=True) # 자동으로 현재시간 입력
  
  def __str__(self):
    return f"{self.id},{self.name}"

w1120/w01/member/views.py
from django.shortcuts import render
from member.models import Member
import base64

def product(request):
  if request.method == "GET":
    # 쿠키 읽어오기
    c_pId = request.COOKIES.get('c_pId',"")
    c_pId = base64.b64decode(c_pId).decode() # 디코딩
    c_pName = request.COOKIES.get('c_pName',"")
    c_pName = base64.b64decode(c_pName).decode() # 디코딩
    context = {"c_pId":c_pId,'c_pName':c_pName}
    return render(request,'product.html',context)
  else:
    # 쿠키저장
    pId = request.POST.get("pId")
    pName = request.POST.get("pName")
    pOption = request.POST.get("pOption")
    saveProduct = request.POST.get("saveProduct")
    print(pId,pName,pOption,saveProduct)
    response = render(request,'index.html')
   
    if saveProduct is not None: #체크가 되어 있으면
      # 쿠키저장
       # BASE64 한글 인코딩 
      # base64.b64encode(pId.encode()).decode()
      response.set_cookie('c_pId',(base64.b64encode(pId.encode()).decode()))
      response.set_cookie('c_pName',(base64.b64encode(pName.encode()).decode()))
    else:
      response.delete_cookie('c_pId')  
      response.delete_cookie('c_pName')  
      
    return response  
      
    


def login2(request):
  if request.method == "GET":
    cookId = request.COOKIES.get('cookId','')
    context = {"cookId":cookId}  
    return render(request,'login2.html',context)
    
  else:
    response = render(request,'index.html')
    # 3개정보 
    id = request.POST.get('id')
    pw = request.POST.get('pw')
    saveId = request.POST.get('saveId')
    if saveId is not None:
      response.set_cookie('cookId',id,max_age=60*60)
    else:
      response.delete_cookie('cookId')
    return response



# 로그인페이지
## 쿠키정보검색 : request.COOKIES.get('이름')
## 쿠키저장 : response.set_cookie('key','value')
## 쿠키삭제 : response.delete_cookie('key')
def login(request):
  if request.method == "GET":
    print("쿠키정보 : ",request.COOKIES)
    print("cookinfo 쿠키정보 : ",request.COOKIES.get('cookinfo'))
    saveId = request.COOKIES.get('saveId','')
    print("saveId :",saveId)
    context = {"saveId":saveId}
    response = render(request,'login.html',context)
    # 쿠키 설정(저장)
    # max_age가 없으면 브라우저 종료시 삭제, max_age=60초*60분 삭제  1달 = 60초*60분*24시간*30일
    ## 쿠키정보 검색
    if not request.COOKIES.get('cookinfo'):
      response.set_cookie('cookinfo','1111',max_age=60*60) 
    return response
  else:
    print("쿠키정보 : ",request.COOKIES)
    id = request.POST.get("id")
    pw = request.POST.get('pw')
    # pw = request.POST['pw'] # 값없을 경우 에러발생
    saveId = request.POST.get("saveId") 
    print("전달받은 정보 :",id,pw,saveId)
    response = render(request,'login.html')
    ## 아이디기억하기 정보가 있으면
    if saveId is not None :
      response.set_cookie('saveId',id,max_age=60*60) # 아이디기억하기 체크가 있으면 쿠키저장
    else:
      response.delete_cookie('saveId') # 아이디기억하기 체크가 없으면 쿠키삭제  
    
    return response 
    

# 회원전체리스트 페이지
def mlist(request):
  qs = Member.objects.all()
  context = {"mlist":qs}
  return render(request,'mlist.html',context)

w1120/w01/member/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>로그인</title>
</head>
<body>
  <h2>로그인</h2>
  <form action="{% url 'member:login' %}" method="post" name="loginFrm">
    {% csrf_token %}
    <label>아이디</label>
    <input type='text' name='id' id='id' value={{saveId}}><br>
    <label>패스워드</label>
    <input type='password' name='pw' id='pw'><br>
    <input type='checkbox' name='saveId' value='1' id='saveId' {%if saveId%}checked{%endif%}>
    <label for="saveId">아이디저장</label><br>
    <input type='submit' value="로그인">

  </form>
  
</body>
</html>

w1120/w01/member/templates/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>로그인</title>
</head>
<body>
  <h2>로그인</h2>
  <h2>{{request.COOKIES}}</h2>
  <form action="{% url 'member:login2' %}" method="post" name="loginFrm">
    {% csrf_token %}
    <label>아이디</label>
    <input type='text' name='id' id='id' value={{cookId}} ><br>
    <label>패스워드</label>
    <input type='password' name='pw' id='pw'><br>
    <input type='checkbox' name='saveId' value='1' id='saveId' {%if cookId%}checked{%endif%}>
    <label for="saveId">아이디저장</label><br>
    <input type='submit' value="로그인">

  </form>
  
</body>
</html>

w1120/w01/member/templates/m2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>회원옵션</title>
</head>
<body>
  <h2>회원옵션</h2>
  <!-- m2.html 에서 회원권번호,금액,옵션을 쿠키에 저장 :데이터 111, 100000, no1-->
  <form action="{% url 'member:m2' %}" method="post" name="loginFrm">
    {% csrf_token %}
    <label>회원권번호</label>
    <input type='text' name='memberId' id='memberId'><br>  
    <label>금액</label>
    <input type='text' name='money' id='money' ><br>
    <label>옵션</label>
    <input type='text' name='option' id='option'><br>
    <input type='checkbox' name='saveMember' value='1' id='saveMember' >
    <label for="saveMember">회원정보저장</label><br>
    <input type='submit' value="회원가입">

  </form>
  
</body>
</html>

w1120/w01/member/templates/mlist.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>회원리스트</title>
  <style>
    *{margin:0; padding:0;}
    .main{margin:30px auto; text-align:center;}
    h2{margin:30px 0;}
    table,th,td{border:1px solid black; border-collapse:collapse;}
    table{width:1200px; margin:30px auto;}
    th,td{height:45px; width:200px;}
    button{width:120px; height:40px;}
    .search{width:190px; height:40px; padding-left:10px; margin-top:50px;}
  </style>
</head>
<body>
  <div class="main">
    <h2>회원리스트</h2>
    <table>
      <tr>
        <th>번호</th>
        <th>아이디</th>
        <th>패스워드</th>
        <th>이름</th>
        <th>닉네임</th>
        <th>가입일</th>
      </tr>
      {% if mlist %}
        {% for m in mlist  %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{m.id}}</td>
            <td>{{m.pw}}</td>
            <td>{{m.name}}</td>
            <td>{{m.nicname}}</td>
            <td>{{m.cdate|date:'Y-m-d H:i'}}</td>
        </tr>
        {% endfor %}
      {% else %}
        <tr>
          <td colspan="6">회원정보가 없습니다.</td>
        </tr>
      {% endif %}
      
    </table>
    <button onclick="location.href='/'">홈으로</button>
    <button onclick="location.href='/member/mwrite/'" >회원정보입력</button>
  </div>
    
</body>
</html>

w1120/w01/member/templates/product.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>상품구매</title>
</head>
<body>
  <h2>상품구매</h2>
  <form action="{% url 'member:product' %}" method="post" name="loginFrm">
    {% csrf_token %}
    <label>상품번호</label>
    <input type='text' name='pId' id='pId' value="{{c_pId}}"><br>
    <label>상품명</label>
    <input type='text' name='pName' id='pName' value="{{c_pName}}"><br>
    <label>상품옵션</label>
    <input type='text' name='pOption' id='pOption'><br>
    <input type='checkbox' name='saveProduct' value='1' id='saveProduct' {% if c_pId%}checked{%endif%} >
    <label for="saveProduct">상품기억하기</label><br>
    <input type='submit' value="상품저장">

  </form>
  
</body>
</html>