w1118/w01Pjt/board/urls.py
from django.urls import path,include
from . import views
app_name='board'   ## name:url시 사용
urlpatterns = [
    path('list/',views.list,name='list' ), 
]

w1118/w01Pjt/home/urls.py
from django.urls import path,include
from . import views
app_name=''   ## name:url시 사용
urlpatterns = [
    path('',views.index,name='index' ), # 메인페이지:index,main,default
]

w1118/w01Pjt/students/urls.py
from django.urls import path,include
from . import views
app_name='students'   ## name:url시 사용
urlpatterns = [
    ## 리스트
    path('list/',views.list,name='list' ), # 학생리스트
    ## 저장
    path('write/',views.write,name='write' ), # 학생입력페이지
    ## 상세
    path('<str:name>/view/',views.view,name='view' ), # 학생상세페이지 <int:no>
    ## 수정1,2,3 - 수정1
    path('<str:name>/modify/',views.modify,name='modify' ), # 학생수정1 - url
    path('modify2/',views.modify2,name='modify2' ), # 학생수정2
    path('<str:name>/modify3/',views.modify3,name='modify3' ), # 학생수정3
    ## 삭제
    path('<str:name>/delete/',views.delete,name='delete' ), # 학생삭제
    
    
    # path('doWrite/',views.doWrite,name='doWrite' ), # 학생입력페이지
]

w1118/w01Pjt/w01Pjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')), #urls추가
    path('students/', include('students.urls')), #urls추가
    path('board/', include('board.urls')), #urls추가
]

w1118/w01Pjt/students/models.py
from django.db import models

# 객체선언 - db테이블 생성
class Student(models.Model):
  name = models.CharField(max_length=100)
  major = models.CharField(max_length=100)
  grade = models.IntegerField(default=0)
  age = models.IntegerField(default=0)
  gender = models.CharField(max_length=10)
  
  def __str__(self):
    return self.name

w1118/w01Pjt/board/views.py
from django.shortcuts import render

def list(request):
  return render(request,'list.html')

w1118/w01Pjt/home/views.py
from django.shortcuts import render

# 메인페이지
def index(request):
  return render(request,'index.html')

w1118/w01Pjt/students/views.py
from django.shortcuts import render,redirect
from students.models import Student

# 학생삭제
def delete(request,name):
  print("삭제정보 :",name)
  Student.objects.get(name=name).delete()
  return redirect("students:list")


# 학생수정페이지1 - url 매개변수로 데이터값을 전달받음.
def modify(request,name):
  if request.method == 'GET':
    print("modify 이름정보:",name)
    # 1개 데이터 가져오기
    qs = Student.objects.filter(name=name)
    context = {'stu':qs[0]}
    return render(request,'update.html',context)
  else:
    print("POST 호출")
    qs = Student.objects.get(name=name)
    print(qs)
    name = request.POST['name']
    major = request.POST['major']
    grade = request.POST['grade']
    age = request.POST['age']
    gender = request.POST['gender']
    print("수정 modify정보 :",name,major,grade,age,gender)
    ## db저장
    qs.major = major
    qs.grade = grade
    qs.age = age
    qs.gender = gender
    qs.save()
    return redirect('students:list')
      

# 학생수정페이지2 - 파라미터
def modify2(request):
  name = request.GET.get('name')
  print("modify2 이름정보:",name)
  # 1개 데이터 가져오기
  qs = Student.objects.filter(name=name)
  context = {'stu':qs[0]}
  return render(request,'update.html',context)

# 학생수정페이지3 - AppName 매개변수로 데이터값을 전달받음.
def modify3(request,name):
  print("modify3 이름정보:",name)
  qs = Student.objects.filter(name=name)
  context = {'stu':qs[0]}
  return render(request,'update.html',context)


# 학생상세페이지
def view(request,name):
  print("이름정보 :",name)
  qs = Student.objects.filter(name=name) # 1개데이터-list, 없을경우 {}
  print(qs)
  context = {'stu':qs[0]}
  return render(request,'view.html',context)
  # qs = Student.objects.get(name = name)  # 없을경우 에러
  # qs = get_object_or_404(Student,name = name)  # 없을경우 구문리턴


# 학생리스트
def list(request):
  qs = Student.objects.all()
  context = {"slist":qs}
  # context 데이터를 전달변수
  return render(request,'list.html',context)


# 학생입력페이지 호출
def write(request):
  if request.method == 'GET':
    ## render : html파일 호출
    print("GET방식으로 들어옴.")
    return render(request,'write.html')
  else:
    print("POST방식으로 들어옴.")
    name = request.POST['name']
    major = request.POST['major']
    grade = request.POST['grade']
    age = request.POST['age']
    gender = request.POST['gender']
    print("입력데이터 : ",name,major,grade,age,gender)
    ## DB저장
    Student.objects.create(name=name,major=major,grade=grade,age=age,gender=gender)
    print("1명 학생저장")
    return redirect("/students/list")





# # 학생입력저장
# def doWrite(request):
#   if request.method == 'POST':
#     name = request.POST['name']
#     major = request.POST['major']
#     grade = request.POST['grade']
#     age = request.POST['age']
#     gender = request.POST['gender']
#     print("입력데이터 : ",name,major,grade,age,gender)
#   else:
#     print("해당되는 데이터가 없습니다.")  
#   return redirect("/")

w1118/w01Pjt/students/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>학생전체리스트</title>
  <style>
    * {margin:0; padding:0; }
    #main{text-align:center; margin-top:50px;}
    button{width:150px; height:40px; text-align:center; }
    table{margin:30px auto;}
    table,th,td{border:1px solid black; border-collapse:collapse; }
    th,td{height:40px; width:150px;}
  </style>
</head>
<body>
  <div id='main'>
    <h2>학생전체리스트</h2>
    <table>
      <tr>
        <th>이름</th>
        <th>학과</th>
        <th>학년</th>
        <th>수정</th>
        <th>삭제</th>
      </tr>
      {% if slist %}
        {% for s in slist %}
        <tr>
          <td><a href="{% url 'students:view' s.name  %}">{{s.name}}</a></td>
          <td>{{s.major}}</td>
          <td>{{s.grade}}</td>
          <td><a href="">수정</a></td>
          <td><a href="">삭제</a></td>
        </tr>
        {% endfor %}
      {% else %}
        <tr>
          <td colspan='5'>입력된 데이터가 없습니다.</td>
        </tr>  
      {% endif %}
    </table>
    <a href='/'><button>메인페이지</button></a>
    <a href='/students/write/'><button>학생입력</button></a>

  </div>
  
</body>
</html>

w1118/w01Pjt/students/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <title>학생성적수정</title>
  <style>
    * {margin:0; padding:0;}
    #main{text-align:center; margin-top:50px;}
    h2 { margin:30px auto;}
    label{width:150px; display: inline-block;}
    .r { width:50px;}
    input[type='button'],button{width:150px; height:40px; text-align:center;}
  </style>
</head>
<body>
  <div id='main'>
    <h2><a href='/'>학생성적수정</a></h2>
    {% comment %} <form action="{% url 'students:modify' stu.name %}" method='post' name='sfrm'> {% endcomment %}
    <form action="/students/{{stu.name}}/modify/" method='post' name='sfrm'>
      {% csrf_token %}
      <label>이름</label>
      {{stu.name}}<br>
      <input type='hidden' name='name' class='name' value='{{stu.name}}'><br>
      <label>학과</label>
      <input type='text' name='major' value='{{stu.major}}'><br>
      <label>학년</label>
      <input type='text' name='grade' value='{{stu.grade}}'><br>
      <label>나이</label>
      <input type='text' name='age' value='{{stu.age}}'><br>
      <label>성별</label>
      <input type='radio' name='gender' id='M' value='M' {%if 'M' in stu.gender%}checked{%endif%} >
      <label class='r' for='M'>남자</label>
      <input type='radio' name='gender' id='F' value='F' {%if 'F' in stu.gender%}checked{%endif%} >
      <label class='r' for='F'>여자</label>
      <br><br>
      <input type='button' onclick='saveChk()' value='수정'>
      <button type='button' onclick='cancel()'>수정취소</button>
    </form>
    <script>
      function cancel(){
        location.href='/students/list/' 
      }
      function saveChk(){
        if ($(".name").val().length<2){
          alert("이름은 2자리 이상 입력하셔야 합니다.");
          $(".name").focus();
          return false;
        }else{
          alert("데이터를 전송합니다.");
          sfrm.submit();
        }

      }
    </script>
  </div>
  
</body>
</html>

w1118/w01Pjt/students/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src='https://code.jquery.com/jquery-latest.min.js'></script>
  <title>학생상세페이지</title>
  <style>
    * {margin:0; padding:0; }
    #main{text-align:center; margin-top:50px;}
    table{margin:30px auto;}
    table,th,td{border:1px solid black; border-collapse:collapse; }
    th,td{height:40px; width:150px;}
    button{width:120px; height:40px;}
    .c2{width:220px;}
  </style>
</head>
<body>
  <div id='main'>
    <h2>학생상세페이지</h2>
    <table>
      <tr>
        <th class='c1'>타이틀</th>
        <th class='c2'>정보</th>
      </tr>
      {% if stu %}
        <tr>
          <td>이름</td>
          <td>{{stu.name}}</td>
        </tr>
        <tr>
          <td>학과</td>
          <td>{{stu.major}}</td>
        </tr>
        <tr>
          <td>학년</td>
          <td>{{stu.grade}}</td>
        </tr>
        <tr>
          <td>나이</td>
          <td>{{stu.age}}</td>
        </tr>
        <tr>
          <td>성별</td>
          <td>{{stu.gender}}</td>
        </tr>
      {% else %}
        <tr>
          <td colspan='2'>데이터가 존재하지 않습니다.</td>
        </tr>  
      {% endif %}
    </table>
    <a href="/students/list"><button>리스트</button></a>

    <a href="/students/{{stu.name}}/modify"><button>수정1-url</button></a>
    <a href="/students/modify2?name={{stu.name}}"><button>수정2-파라미터</button></a>
    <a href="{% url 'students:modify3' stu.name %}"><button>수정3-appName</button></a>
    
    <button type='button' onclick="deleteBtn('{{stu.name}}')">삭제</button>
    <script>
      function deleteBtn(name){
        if(confirm(name + "님 학생정보를 삭제하시겠습니까?")){
          location.href = "/students/"+name+'/delete/'
          // /:root, ./:현재폴더, ../:이전폴더
          //location.href = "../../"+name+'/delete/'
        }
      }
    </script>
  </div>
  
</body>
</html>

w1118/w01Pjt/students/templates/write.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <title>학생성적입력</title>
  <style>
    * {margin:0; padding:0;}
    #main{text-align:center; margin-top:50px;}
    h2 { margin:30px auto;}
    label{width:150px; display: inline-block;}
    .r { width:50px;}
    input[type='button'],button{width:150px; height:40px; text-align:center;}
  </style>
</head>
<body>
  <div id='main'>
    <h2><a href='/'>학생성적입력</a></h2>
    {% comment %} <form action="{% url 'students:write' %}" method='post' name='sfrm'> {% endcomment %}
    <form action="/students/write/" method='post' name='sfrm'>
      {% csrf_token %}
      <label>이름</label>
      <input type='text' name='name' class='name'><br>
      <label>학과</label>
      <input type='text' name='major'><br>
      <label>학년</label>
      <input type='text' name='grade'><br>
      <label>나이</label>
      <input type='text' name='age'><br>
      <label>성별</label>
      <input type='radio' name='gender' id='M' value='M'>
      <label class='r' for='M'>남자</label>
      <input type='radio' name='gender' id='F' value='F'>
      <label class='r' for='F'>여자</label>
      <br><br>
      <input type='button' onclick='saveChk()' value='저장'>
      <button type='button' onclick='cancel()'>취소</button>
    </form>
    <script>
      function cancel(){
        location.href='/students/list/' 
      }
      function saveChk(){
        if ($(".name").val().length<2){
          alert("이름은 2자리 이상 입력하셔야 합니다.");
          $(".name").focus();
          return false;
        }else{
          alert("데이터를 전송합니다.");
          sfrm.submit();
        }

      }
    </script>
  </div>
  
</body>
</html>