w1121/w01/member/urls.py
from django.urls import path,include
from . import views

app_name='member'
urlpatterns = [
    ## 회원정보관련
    path('mdelete/<str:id>/', views.mdelete, name='mdelete'), # 회원정보삭제
    path('mwrite/', views.mwrite, name='mwrite'), # 회원정보입력
    path('mupdate/<str:id>/', views.mupdate, name='mupdate'), # 회원정보수정
    path('mview/<str:id>/', views.mview, name='mview'), # 회원상세
    path('mlist/', views.mlist, name='mlist'), # 회원리스트
    
    ## 로그인관련
    path('login/', views.login, name='login'), # 로그인
    path('logout/', views.logout, name='logout'), #로그아웃
]

w1121/w01/member/models.py
from django.db import models

class Member(models.Model):
  id = models.CharField(max_length=50,primary_key=True)
  pw = models.CharField(max_length=100)
  name = models.CharField(max_length=50)
  nickname = models.CharField(max_length=50)
  tel = models.CharField(max_length=50,default='010-1111-1111')
  gender = models.CharField(max_length=10,default='남자')
  hobby = models.CharField(max_length=50,default='game')
  mdate = models.DateTimeField(auto_now=True)
  
  def __str__(self):
    return f"{self.id},{self.name},{self.nickname}"
  

w1121/w01/member/views.py
from django.shortcuts import render,redirect
from member.models import Member

# 회원정보삭제
def mdelete(request,id):
  print("회원정보 :",id)
  Member.objects.get(id=id).delete()
  # return render(request,'mlist.html')
  return redirect('member:mlist')
  

# 회원정보수정
def mupdate(request,id):
  if request.method == "GET":
    print("회원정보 :",id)
    qs = Member.objects.filter(id=id)
    context = {"mem":qs[0]}
    return render(request,'mupdate.html',context)
  else:
    print("id : ",id)
    id = request.session['session_id'] # admin이 아니면 세션을 가지고 저장.
    ## 관리자 로그인이면, id를 가져와서 저장
    if request.session['session_id']=='admin':
      id = request.POST.get("id")
    pw = request.POST.get("pw")
    name = request.POST.get("name")
    nickname = request.POST.get("nickname")
    tel = request.POST.get("tel")
    gender = request.POST.get("gender")
    hobbys = request.POST.getlist("hobby")
    hobby = ",".join(hobbys)
    
    qs = Member.objects.get(id=id)
    qs.pw = pw
    qs.name = name
    qs.nickname = nickname
    qs.tel = tel
    qs.gender = gender
    qs.hobby = hobby
    qs.save()
    
    return redirect('member:mlist')



# 회원정보입력
def mwrite(request):
  if request.method == "GET":
    return render(request,'mwrite.html')
  else:
    id = request.POST.get("id")
    pw = request.POST.get("pw")
    name = request.POST.get("name")
    nickname = request.POST.get("nickname")
    tel = request.POST.get("tel")
    gender = request.POST.get("gender")
    hobbys = request.POST.getlist("hobby")
    hobby = ','.join(hobbys)
    Member.objects.create(id=id,pw=pw,name=name,nickname=nickname,tel=tel,gender=gender,hobby=hobby)
    # qs = Member(id=id,pw=pw,name=name,nickname=nickname,tel=tel,gender=gender,hobby=hobby)
    # qs.save()
    return redirect("member:mlist")
    
# 회원상세
def mview(request,id):
  print("아이디 :",id)
  qs = Member.objects.filter(id=id)
  context = {"mem":qs[0]}
  return render(request,'mview.html',context)

# 회원리스트
def mlist(request):
  id = request.session['session_id']
  if id == 'admin':
    qs = Member.objects.all()
  else:
    qs = Member.objects.filter(id=id)
  context = {"mlist":qs}
  return render(request,'mlist.html',context)


# 로그아웃
def logout(request):
  request.session.clear() # 전체섹션 삭제
  ## del request.session['session_id'] 해당 섹션 삭제
  return redirect("/")

# 로그인페이지, 로그인버튼확인
def login(request):
  if request.method == "GET":
    return render(request,'login.html')
  else:
    id = request.POST.get('id')
    pw = request.POST.get('pw')
    qs = Member.objects.filter(id=id,pw=pw)
    if qs:
      msg = "로그인 되었습니다."
      print(msg)
      ## 세션연결
      request.session['session_id'] = id
      request.session['session_nickname'] = qs[0].nickname
      
      return redirect('index')
    else:
      msg = "아이디 또는 패스워드가 일치하지 않습니다."
      print(msg)
      return render(request,'login.html',{"login_msg":msg})  

w1121/w01/member/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <script src='http://code.jquery.com/jquery-latest.min.js'></script>
    <link rel='stylesheet' href="{% static 'css/style2.css' %}">
    <title>로그인</title>
    <script>
        // 아이디와 패스워드가 일치하지 않을때
        if ('{{login_msg}}' != ''){
            alert('{{login_msg}}');
        }
    </script>
</head>
<body>
<div id="wrap">
    <div id="header">
        <h1>
            <a href="/" id="h_logo"></a>
        </h1>
    </div>
    <div id="container">
        <div id="content">
            <div style="margin-bottom: 7px"></div>
            <form action="{% url 'member:login' %}" method='post' name='mfrm'>
                {% csrf_token %}
                <fieldset style="border: 0">
                    <div class="id_area">
                        <div class="input_row" id="id_area">
                            <span class="input_box">
                                <input type="text" name="id" id="uId" class="int" placeholder="아이디">
                            </span>
                        </div>
                    </div>
                    <div class="pw_area">
                        <div class="input_row" id="pw_area">
                            <span class="input_box">
                                <input type="text" name="pw" id="uPw" class="int" placeholder="비밀번호">
                            </span>
                        </div>
                    </div>
                    <input class="btn_login" type="button" onclick="writeBtn()" value="로그인">
                </fieldset>
            </form>
            <script>
                function writeBtn(){
                    if ($("#uId").val().length < 2){
                        alert("아이디는 2자리 이상 입력하셔야 합니다.")
                        $("#uId").focus();
                        return false;
                    }
                    alert("로그인을 진행합니다.")
                    mfrm.submit()
                }
            </script>
        </div>
    </div>
</div>
</body>
</html>

w1121/w01/member/templates/mlist.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>게시판</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="/static/css/style.css">
  <link rel="stylesheet" href="{% static  'css/notice_list.css' %}">
</head>
<body>
<section>
    <h1>회원리스트</h1>
    <div class="wrapper">
      <form action="/search" name="search" method="post">
        <select name="category" id="category">
          <option value="0">전체</option>
          <option value="name">이름</option>
          <option value="id">아이디</option>
        </select>

        <div class="title">
          <input type="text" size="16">
        </div>
  
        <button type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="15%">
        <col width="15%">
        <col width="15%">
        <col width="20%">
        <col width="20%">
        <col width="15%">
      </colgroup>
      <!-- 제목부분 -->
      <tr>
        <th>번호</th>
        <th>아이디</th>
        <th>패스워드</th>
        <th>이름</th>
        <th>닉네임</th>
        <th>가입일</th>
      </tr>
      <!-- 내용부분 -->
       {% if mlist %}
        {% for m in mlist %}
          <tr>
            <td><span class="table-notice">{{forloop.counter}}</span></td>
            <td class="table-title"><a href="/member/mview/{{m.id}}/">{{m.id}}</a></td>
            <td>{{m.pw}}</td>
            <td>{{m.name}}</td>
            <td>{{m.nickname}}</td>
            <td>{{m.mdate|date:'Y-m-d'}}</td>
          </tr>
        {% endfor %}
      {%else%}
        <tr>
          <td colspan='6'>데이터가 없습니다.</td>
        </tr>
      {%endif%}
    </table>

    <ul class="page-num">
      <li class="first"></li>
      <li class="prev"></li>
      <li class="num"><div>1</div></li>
      <li class="next"></li>
      <li class="last"></li>
    </ul>

    <a href="/"><div class="write">홈으로</div></a>
    <a href="/member/mwrite/"><div class="write">쓰기</div></a>
  </section>

</body>
</html>

w1121/w01/member/templates/mupdate.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <title>회원정보수정</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/write.css'%}">
  <style>
    input[type='radio'],input[type='checkbox']{width:20px; margin-right:3px; vertical-align:middle;}
    label{margin-right:20px;}
  </style>
  <script>
    $(function(){
      $(".write").click(function(){
        if($("#id").val().length<2){
          alert("아이디는 2자리 이상입력하셔야 가능합니다.");
          $("#id").focus();
          return false;
        }
        writeFrm.submit();
      });
    })
  </script>
</head>
<body>
<section>
    <h1>회원정보수정</h1>
    <hr>
    <form action="{% url 'member:mupdate' mem.id  %}" name="writeFrm" method="post">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>아이디</th>
          <input type="hidden" name="id" id="id" value="{{mem.id}}">
          <td>
            {{mem.id}}
          </td>
        </tr>
        <tr>
          <th>패스워드</th>
          <td>
            <input type="password" name="pw" value="{{mem.pw}}">
          </td>
        </tr>
        <tr>
          <th>이름</th>
          <td>
            <input type="text" name="name" value="{{mem.name}}">
          </td>
        </tr>
        <tr>
          <th>닉네임</th>
          <td>
            <input type="text" name="nickname" value="{{mem.nickname}}">
          </td>
        </tr>
        <tr>
          <th>전화번호</th>
          <td>
            <input type="text" name="tel" value="{{mem.tel}}">
          </td>
        </tr>
        <tr>
          <th>성별</th>
          <td>
            <input type="radio" name="gender" id='male' value="남자" {%if '남자' in mem.gender%}checked{%endif%}  >
            <label for="male">남자</label>
            <input type="radio" name="gender" id='female' value="여자" {%if '여자' in mem.gender%}checked{%endif%}>
            <label for="female">여자</label>
          </td>
        </tr>
        <tr>
          <th>취미</th>
          <td>
            <input type="checkbox" name="hobby" id='game' value="game" {%if 'game' in mem.hobby%}checked{%endif%}>
            <label for="game">게임</label>
            <input type="checkbox" name="hobby" id='golf' value="golf" {%if 'golf' in mem.hobby%}checked{%endif%}>
            <label for="golf">골프</label>
            <input type="checkbox" name="hobby" id='swim' value="swim" {%if 'swim' in mem.hobby%}checked{%endif%}>
            <label for="swim">수영</label>
            <input type="checkbox" name="hobby" id='run' value="run" {%if 'run' in mem.hobby%}checked{%endif%}>
            <label for="run">조깅</label>
            <input type="checkbox" name="hobby" id='book' value="book" {%if 'book' in mem.hobby%}checked{%endif%}>
            <label for="book">독서</label>
            
          </td>
        </tr>
        
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="button" class="write">수정완료</button>
        <button type="button" class="cancel" onclick="javascript:location.href='/member/mlist/'">취소</button>
      </div>
    </form>

  </section>

</body>
</html>

w1121/w01/member/templates/mview.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>회원상세보기</title>
  <script src='http://code.jquery.com/jquery-latest.min.js'></script>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/read.css'%}">
  <script>
    $(function(){
      $(".delBtn").click(function(){
        if(confirm("{{mem.id}} 님 데이터를 삭제하시겠습니까?")){
          alert("데이터 삭제");
          location.href='/member/mdelete/{{mem.id}}/'
        }
      })
    });
  </script>
</head>
<body>
<section>
    <h1>회원상세보기</h1>

    <table>
      <colgroup>
        <col width="20%">
        <col width="80%">
      </colgroup>
      <tr>
        <th>아이디</th>
        <th>{{mem.id}}</th>
      </tr>
      <tr>
        <td><strong>패스워드</strong></td>
        <td>{{mem.pw}}</td>
      </tr>
      <tr>
        <td><strong>이름</strong></td>
        <td>{{mem.name}}</td>
      </tr>
      <tr>
        <td><strong>닉네임</strong></td>
        <td>{{mem.nickname}}</td>
      </tr>
      <tr>
        <td><strong>전화번호</strong></td>
        <td>{{mem.tel}}</td>
      </tr>
      <tr>
        <td><strong>성별</strong></td>
        <td>{{mem.gender}}</td>
      </tr>
      <tr>
        <td><strong>취미</strong></td>
        <td>{{mem.hobby}}</td>
      </tr>
      
      <tr>
        <td colspan="3"><strong>다음</strong> <span class="separator">|</span> 홍길동</td>
      </tr>
      <tr>
        <td colspan="3"><strong>이전</strong> <span class="separator">|</span> 유관순</td>
      </tr>
    </table>

    <a href="{% url 'member:mlist' %}"><div class="list">회원리스트</div></a>
    <a class='delBtn'><div class="list">회원삭제</div></a>
    <a href="{% url 'member:mupdate' mem.id %}"><div class="list">회원수정</div></a>
  </section>
</body>
</html>

w1121/w01/member/templates/mwrite.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <title>글쓰기</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/write.css'%}">
  <style>
    input[type='radio'],input[type='checkbox']{width:20px; margin-right:3px; vertical-align:middle;}
    label{margin-right:20px;}
  </style>
  <script>
    $(function(){
      $(".write").click(function(){
        if($("#id").val().length<2){
          alert("아이디는 2자리 이상입력하셔야 가능합니다.");
          $("#id").focus();
          return false;
        }
        writeFrm.submit();
      });
    })
  </script>
</head>
<body>
<section>
    <h1>회원정보입력</h1>
    <hr>
    <form action="{% url 'member:mwrite' %}" name="writeFrm" method="post">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>아이디</th>
          <td>
            <input type="text" name="id" id="id">
          </td>
        </tr>
        <tr>
          <th>패스워드</th>
          <td>
            <input type="password" name="pw">
          </td>
        </tr>
        <tr>
          <th>이름</th>
          <td>
            <input type="text" name="name">
          </td>
        </tr>
        <tr>
          <th>닉네임</th>
          <td>
            <input type="text" name="nickname">
          </td>
        </tr>
        <tr>
          <th>전화번호</th>
          <td>
            <input type="text" name="tel">
          </td>
        </tr>
        <tr>
          <th>성별</th>
          <td>
            <input type="radio" name="gender" id='male' value="남자">
            <label for="male">남자</label>
            <input type="radio" name="gender" id='female' value="여자">
            <label for="female">여자</label>
          </td>
        </tr>
        <tr>
          <th>취미</th>
          <td>
            <input type="checkbox" name="hobby" id='game' value="game">
            <label for="game">게임</label>
            <input type="checkbox" name="hobby" id='golf' value="golf">
            <label for="golf">골프</label>
            <input type="checkbox" name="hobby" id='swim' value="swim">
            <label for="swim">수영</label>
            <input type="checkbox" name="hobby" id='run' value="run">
            <label for="run">조깅</label>
            <input type="checkbox" name="hobby" id='book' value="book">
            <label for="book">독서</label>
            
          </td>
        </tr>
        
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="button" class="write">작성완료</button>
        <button type="button" class="cancel" onclick="javascript:location.href='/member/mlist/'">취소</button>
      </div>
    </form>

  </section>

</body>
</html>